### ISSUE TITLE
Gateway ID is missing one digit

### ISSUE THREAD

**Issue by tkerby** [things4u/ESP-1ch-Gateway-v3.0#2]
I've noticed the ID reported is incorrect - the zero (in bold below) is missing

MAC: 5c:cf:7f:c1:**0**f:d7:
SX1276 detected, starting.
Gateway ID: 5CCF7FFFFFC1FD7, Listening at SF9 on 868.10 Mhz.

Yet TTN sees it as 5CCF7FFFFFC1**0**FD7 N/A      active    now

**Comment by nicoschtein** [comment]
This happens to me too, but it's not that one digit, it's all left zeroes per byte.

**Comment by platenspeler** [comment]
@tkerby 

Thanks for alrting me. Indeed it has not much to do with the program running, but only the Serial output during Setup. I will make an update to the code shortly.

**Comment by tkerby** [comment]
Thanks for the update. Please note that it also affects the values in the web interface.

**Comment by platenspeler** [comment]
@nicoschtein,

Dit is most likely something different.  Byte 4 and 5 of the GatewayId are oxff.

**Comment by platenspeler** [comment]
Done, please check.

**Comment by tkerby** [comment]
That didn't work for me.  I dont think you mean 10 in the code - I think you mean 16 for "if(digit <10)" in the code below

```
void printHexDigit(uint8_t digit)
{
    // utility function for printing Hex Values with leading 0
    if(digit <10)
        Serial.print('0');
    Serial.print(digit,HEX);
}
```

Note that the code you have added only works for serial - the incorrect values are still displayed on the web interface too.  You might be better doing some string formatting and returning a string to print. See examples here: https://forum.arduino.cc/index.php?topic=38107.0

**Comment by tkerby** [comment]
Apologies, missed the web code.  It should be 16 rather than 10 too

`	if (MAC_array[0]<16) response +='0'; response +=String(MAC_array[0],HEX);	// The MAC array is always returned in lowercase
	if (MAC_array[1]<16) response +='0'; response +=String(MAC_array[1],HEX); 
	if (MAC_array[2]<16) response +='0'; response +=String(MAC_array[2],HEX); 
	response +="ffff"; 
	if (MAC_array[3]<16) response +='0'; response +=String(MAC_array[3],HEX); 
	if (MAC_array[4]<16) response +='0'; response +=String(MAC_array[4],HEX); 
	if (MAC_array[5]<16) response +='0'; response +=String(MAC_array[5],HEX);
	response+="</tr>";
	response +="</table>";`

**Comment by platenspeler** [comment]
No need for apologies. I tried to do a quick fix but did not have a gateway at have with a value between 10 and 0x10. So I messed up. Will post a fix tomorrow probably.

Van: tkerby [mailto:notifications@github.com]
Verzonden: dinsdag 1 november 2016 18:49
Aan: things4u/ESP-1ch-Gateway-v3.0 <ESP-1ch-Gateway-v3.0@noreply.github.com>
CC: Maarten Westenberg <mw12554@hotmail.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [things4u/ESP-1ch-Gateway-v3.0] Gateway ID is missing one digit (#2)


Apologies, missed the web code. It should be 16 rather than 10 too

if (MAC_array[0]<16) response +='0'; response +=String(MAC_array[0],HEX); // The MAC array is always returned in lowercase
if (MAC_array[1]<16) response +='0'; response +=String(MAC_array[1],HEX);
if (MAC_array[2]<16) response +='0'; response +=String(MAC_array[2],HEX);
response +="ffff";
if (MAC_array[3]<16) response +='0'; response +=String(MAC_array[3],HEX);
if (MAC_array[4]<16) response +='0'; response +=String(MAC_array[4],HEX);
if (MAC_array[5]<16) response +='0'; response +=String(MAC_array[5],HEX);
response+="</tr>";
response +="</table>";
