### ISSUE TITLE
Update channel and SF through web

### ISSUE THREAD

**Issue by tkerby** [things4u/ESP-1ch-Gateway-v3.0#3]
Would be really useful to be able to change the frequency and spreading factor through the web interface rather than recompiling.

**Comment by platenspeler** [comment]
In this case we need to store Freq and SF in SPIFF filesystem to prevent from losing these settings at reboot of the gateway.

**Comment by platenspeler** [comment]
Yes it definitely would. But we should then add these values to SPIFF filesystem to avoid losing them with a reboot. In short: Working on this and several other functions ☺

Maarten

Van: tkerby [mailto:notifications@github.com]
Verzonden: zaterdag 29 oktober 2016 13:46
Aan: things4u/ESP-1ch-Gateway-v3.0 <ESP-1ch-Gateway-v3.0@noreply.github.com>
Onderwerp: [things4u/ESP-1ch-Gateway-v3.0] Update channel and SF through web (#3)


Would be really useful to be able to change the frequency and spreading factor through the web interface rather than recompiling.

**Comment by platenspeler** [comment]
I have made a version (3.3) with several enhancements including setting SF and FREQ from the webserver. It will be available shortly.

**Comment by Deepdone** [comment]
@platenspeler Hi,I use the version 3.3.0,but I can't compile successfully.Err message:'readConfig' was not declared in this scope

**Comment by platenspeler** [comment]
Thanks,

At first sight it appears that one of th enecessary files was not copied to github.
I updated github with this file _loraFiles.ino.

Can you please confirm it works for you now?

Thanks,

Maarten

Van: Deepdone [mailto:notifications@github.com]
Verzonden: dinsdag 10 januari 2017 10:50
Aan: things4u/ESP-1ch-Gateway-v3.0 <ESP-1ch-Gateway-v3.0@noreply.github.com>
CC: Maarten Westenberg <mw12554@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [things4u/ESP-1ch-Gateway-v3.0] Update channel and SF through web (#3)


@platenspeler<https://github.com/platenspeler> Hi,I use the version 3.3.0,but I can't compile successfully.Err message:'readConfig' was not declared in this scope

**Comment by Deepdone** [comment]
Thanks for your reply！It works well @platenspeler

**Comment by platenspeler** [comment]
Thanks. Good luck!
