### ISSUE TITLE
Status updates not being interpreted by TTN

### ISSUE THREAD

**Issue by jpmeijers** [things4u/ESP-1ch-Gateway-v3.0#9]
https://github.com/things4u/ESP-1ch-Gateway-v3.0/blob/master/ESP-sc-gway30/ESP-sc-gway30.ino#L755

`sprintf(stat_timestamp, "%d-%d-%2d %d:%d:%02d CET", year(),month(),day(),hour(),minute(),second());`
had to be changed to
`sprintf(stat_timestamp, "%04d-%02d-%02d %02d:%02d:%02d CET", year(),month(),day(),hour(),minute(),second());`
otherwise the TTN NOC did not correctly parse/interpret the Status updates.

**Comment by platenspeler** [comment]
Dank je wel, ik neem deze mee voor de volgende release op github.

Maarten


Van: JP Meijers [mailto:notifications@github.com]
Verzonden: vrijdag 9 december 2016 0:16
Aan: things4u/ESP-1ch-Gateway-v3.0 <ESP-1ch-Gateway-v3.0@noreply.github.com>
Onderwerp: [things4u/ESP-1ch-Gateway-v3.0] Status updates not being interpreted by TTN (#9)


https://github.com/things4u/ESP-1ch-Gateway-v3.0/blob/master/ESP-sc-gway30/ESP-sc-gway30.ino#L755

sprintf(stat_timestamp, "%d-%d-%2d %d:%d:%02d CET", year(),month(),day(),hour(),minute(),second());
had to be changed to
sprintf(stat_timestamp, "%04d-%02d-%02d %02d:%02d:%02d CET", year(),month(),day(),hour(),minute(),second());
otherwise the TTN NOC did not correctly parse/interpret the Status updates.

**Comment by platenspeler** [comment]
Implemented in latest release.
